// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bgp.proto

package apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NextHopAttribute struct {
	NextHop              string   `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextHopAttribute) Reset()         { *m = NextHopAttribute{} }
func (m *NextHopAttribute) String() string { return proto.CompactTextString(m) }
func (*NextHopAttribute) ProtoMessage()    {}
func (*NextHopAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e12fe45eec524a6, []int{0}
}

func (m *NextHopAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextHopAttribute.Unmarshal(m, b)
}
func (m *NextHopAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextHopAttribute.Marshal(b, m, deterministic)
}
func (m *NextHopAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextHopAttribute.Merge(m, src)
}
func (m *NextHopAttribute) XXX_Size() int {
	return xxx_messageInfo_NextHopAttribute.Size(m)
}
func (m *NextHopAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_NextHopAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_NextHopAttribute proto.InternalMessageInfo

func (m *NextHopAttribute) GetNextHop() string {
	if m != nil {
		return m.NextHop
	}
	return ""
}

type OriginAttribute struct {
	Origin               uint32   `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginAttribute) Reset()         { *m = OriginAttribute{} }
func (m *OriginAttribute) String() string { return proto.CompactTextString(m) }
func (*OriginAttribute) ProtoMessage()    {}
func (*OriginAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e12fe45eec524a6, []int{1}
}

func (m *OriginAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginAttribute.Unmarshal(m, b)
}
func (m *OriginAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginAttribute.Marshal(b, m, deterministic)
}
func (m *OriginAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginAttribute.Merge(m, src)
}
func (m *OriginAttribute) XXX_Size() int {
	return xxx_messageInfo_OriginAttribute.Size(m)
}
func (m *OriginAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_OriginAttribute proto.InternalMessageInfo

func (m *OriginAttribute) GetOrigin() uint32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

type BGPPath struct {
	Prefix               *Prefix           `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NextHop              *NextHopAttribute `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Origin               *OriginAttribute  `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BGPPath) Reset()         { *m = BGPPath{} }
func (m *BGPPath) String() string { return proto.CompactTextString(m) }
func (*BGPPath) ProtoMessage()    {}
func (*BGPPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e12fe45eec524a6, []int{2}
}

func (m *BGPPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BGPPath.Unmarshal(m, b)
}
func (m *BGPPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BGPPath.Marshal(b, m, deterministic)
}
func (m *BGPPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BGPPath.Merge(m, src)
}
func (m *BGPPath) XXX_Size() int {
	return xxx_messageInfo_BGPPath.Size(m)
}
func (m *BGPPath) XXX_DiscardUnknown() {
	xxx_messageInfo_BGPPath.DiscardUnknown(m)
}

var xxx_messageInfo_BGPPath proto.InternalMessageInfo

func (m *BGPPath) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *BGPPath) GetNextHop() *NextHopAttribute {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *BGPPath) GetOrigin() *OriginAttribute {
	if m != nil {
		return m.Origin
	}
	return nil
}

type IPv6UnicastRoute struct {
	Path                 []*BGPPath `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IPv6UnicastRoute) Reset()         { *m = IPv6UnicastRoute{} }
func (m *IPv6UnicastRoute) String() string { return proto.CompactTextString(m) }
func (*IPv6UnicastRoute) ProtoMessage()    {}
func (*IPv6UnicastRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e12fe45eec524a6, []int{3}
}

func (m *IPv6UnicastRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv6UnicastRoute.Unmarshal(m, b)
}
func (m *IPv6UnicastRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv6UnicastRoute.Marshal(b, m, deterministic)
}
func (m *IPv6UnicastRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv6UnicastRoute.Merge(m, src)
}
func (m *IPv6UnicastRoute) XXX_Size() int {
	return xxx_messageInfo_IPv6UnicastRoute.Size(m)
}
func (m *IPv6UnicastRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv6UnicastRoute.DiscardUnknown(m)
}

var xxx_messageInfo_IPv6UnicastRoute proto.InternalMessageInfo

func (m *IPv6UnicastRoute) GetPath() []*BGPPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func init() {
	proto.RegisterType((*NextHopAttribute)(nil), "apis.NextHopAttribute")
	proto.RegisterType((*OriginAttribute)(nil), "apis.OriginAttribute")
	proto.RegisterType((*BGPPath)(nil), "apis.BGPPath")
	proto.RegisterType((*IPv6UnicastRoute)(nil), "apis.IPv6UnicastRoute")
}

func init() { proto.RegisterFile("bgp.proto", fileDescriptor_2e12fe45eec524a6) }

var fileDescriptor_2e12fe45eec524a6 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4a, 0x2f, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0xc8, 0x2c, 0x96, 0xe2, 0x4a, 0x4a, 0x2c,
	0x4e, 0x85, 0x88, 0x28, 0xe9, 0x72, 0x09, 0xf8, 0xa5, 0x56, 0x94, 0x78, 0xe4, 0x17, 0x38, 0x96,
	0x94, 0x14, 0x65, 0x26, 0x95, 0x96, 0xa4, 0x0a, 0x49, 0x72, 0x71, 0xe4, 0xa5, 0x56, 0x94, 0xc4,
	0x67, 0xe4, 0x17, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0xe7, 0x41, 0xd4, 0x28, 0x69,
	0x72, 0xf1, 0xfb, 0x17, 0x65, 0xa6, 0x67, 0xe6, 0x21, 0x54, 0x8b, 0x71, 0xb1, 0xe5, 0x83, 0x85,
	0xc0, 0x6a, 0x79, 0x83, 0xa0, 0x3c, 0xa5, 0x89, 0x8c, 0x5c, 0xec, 0x4e, 0xee, 0x01, 0x01, 0x89,
	0x25, 0x19, 0x42, 0x2a, 0x5c, 0x6c, 0x05, 0x45, 0xa9, 0x69, 0x99, 0x15, 0x60, 0x35, 0xdc, 0x46,
	0x3c, 0x7a, 0x20, 0x87, 0xe8, 0x05, 0x80, 0xc5, 0x82, 0xa0, 0x72, 0x42, 0x86, 0x48, 0xf6, 0x32,
	0x81, 0xd5, 0x89, 0x41, 0xd4, 0xa1, 0xbb, 0x10, 0xee, 0x1e, 0x21, 0x5d, 0xb8, 0xe5, 0xcc, 0x60,
	0x0d, 0xa2, 0x10, 0x0d, 0x68, 0x6e, 0x84, 0xbb, 0xc9, 0x94, 0x4b, 0xc0, 0x33, 0xa0, 0xcc, 0x2c,
	0x34, 0x2f, 0x33, 0x39, 0xb1, 0xb8, 0x24, 0x28, 0x1f, 0xe4, 0x7e, 0x45, 0x2e, 0x96, 0x82, 0xc4,
	0x92, 0x0c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x5e, 0x88, 0x01, 0x50, 0x87, 0x07, 0x81,
	0xa5, 0x92, 0xd8, 0xc0, 0x61, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x54, 0xdc, 0x37,
	0x4a, 0x01, 0x00, 0x00,
}
