// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prefixsid.proto

package apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// https://tools.ietf.org/html/draft-dawra-bess-srv6-services-02#section-2.1.1
type SRv6StructureSubSubTLV struct {
	LocalBlockLength     uint32   `protobuf:"varint,1,opt,name=local_block_length,json=localBlockLength,proto3" json:"local_block_length,omitempty"`
	LocalNodeLength      uint32   `protobuf:"varint,2,opt,name=local_node_length,json=localNodeLength,proto3" json:"local_node_length,omitempty"`
	FunctionLength       uint32   `protobuf:"varint,3,opt,name=function_length,json=functionLength,proto3" json:"function_length,omitempty"`
	ArgumentLength       uint32   `protobuf:"varint,4,opt,name=argument_length,json=argumentLength,proto3" json:"argument_length,omitempty"`
	TranspositionLength  uint32   `protobuf:"varint,5,opt,name=transposition_length,json=transpositionLength,proto3" json:"transposition_length,omitempty"`
	TranspositionOffset  uint32   `protobuf:"varint,6,opt,name=transposition_offset,json=transpositionOffset,proto3" json:"transposition_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRv6StructureSubSubTLV) Reset()         { *m = SRv6StructureSubSubTLV{} }
func (m *SRv6StructureSubSubTLV) String() string { return proto.CompactTextString(m) }
func (*SRv6StructureSubSubTLV) ProtoMessage()    {}
func (*SRv6StructureSubSubTLV) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{0}
}

func (m *SRv6StructureSubSubTLV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6StructureSubSubTLV.Unmarshal(m, b)
}
func (m *SRv6StructureSubSubTLV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6StructureSubSubTLV.Marshal(b, m, deterministic)
}
func (m *SRv6StructureSubSubTLV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6StructureSubSubTLV.Merge(m, src)
}
func (m *SRv6StructureSubSubTLV) XXX_Size() int {
	return xxx_messageInfo_SRv6StructureSubSubTLV.Size(m)
}
func (m *SRv6StructureSubSubTLV) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6StructureSubSubTLV.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6StructureSubSubTLV proto.InternalMessageInfo

func (m *SRv6StructureSubSubTLV) GetLocalBlockLength() uint32 {
	if m != nil {
		return m.LocalBlockLength
	}
	return 0
}

func (m *SRv6StructureSubSubTLV) GetLocalNodeLength() uint32 {
	if m != nil {
		return m.LocalNodeLength
	}
	return 0
}

func (m *SRv6StructureSubSubTLV) GetFunctionLength() uint32 {
	if m != nil {
		return m.FunctionLength
	}
	return 0
}

func (m *SRv6StructureSubSubTLV) GetArgumentLength() uint32 {
	if m != nil {
		return m.ArgumentLength
	}
	return 0
}

func (m *SRv6StructureSubSubTLV) GetTranspositionLength() uint32 {
	if m != nil {
		return m.TranspositionLength
	}
	return 0
}

func (m *SRv6StructureSubSubTLV) GetTranspositionOffset() uint32 {
	if m != nil {
		return m.TranspositionOffset
	}
	return 0
}

type SRv6SIDFlags struct {
	// Placeholder for future sid flags
	Flag_1               bool     `protobuf:"varint,1,opt,name=flag_1,json=flag1,proto3" json:"flag_1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRv6SIDFlags) Reset()         { *m = SRv6SIDFlags{} }
func (m *SRv6SIDFlags) String() string { return proto.CompactTextString(m) }
func (*SRv6SIDFlags) ProtoMessage()    {}
func (*SRv6SIDFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{1}
}

func (m *SRv6SIDFlags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6SIDFlags.Unmarshal(m, b)
}
func (m *SRv6SIDFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6SIDFlags.Marshal(b, m, deterministic)
}
func (m *SRv6SIDFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6SIDFlags.Merge(m, src)
}
func (m *SRv6SIDFlags) XXX_Size() int {
	return xxx_messageInfo_SRv6SIDFlags.Size(m)
}
func (m *SRv6SIDFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6SIDFlags.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6SIDFlags proto.InternalMessageInfo

func (m *SRv6SIDFlags) GetFlag_1() bool {
	if m != nil {
		return m.Flag_1
	}
	return false
}

type SRv6TLV struct {
	Tlv                  []*any.Any `protobuf:"bytes,1,rep,name=tlv,proto3" json:"tlv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SRv6TLV) Reset()         { *m = SRv6TLV{} }
func (m *SRv6TLV) String() string { return proto.CompactTextString(m) }
func (*SRv6TLV) ProtoMessage()    {}
func (*SRv6TLV) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{2}
}

func (m *SRv6TLV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6TLV.Unmarshal(m, b)
}
func (m *SRv6TLV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6TLV.Marshal(b, m, deterministic)
}
func (m *SRv6TLV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6TLV.Merge(m, src)
}
func (m *SRv6TLV) XXX_Size() int {
	return xxx_messageInfo_SRv6TLV.Size(m)
}
func (m *SRv6TLV) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6TLV.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6TLV proto.InternalMessageInfo

func (m *SRv6TLV) GetTlv() []*any.Any {
	if m != nil {
		return m.Tlv
	}
	return nil
}

// https://tools.ietf.org/html/draft-dawra-bess-srv6-services-02#section-2.1.1
type SRv6InformationSubTLV struct {
	Sid              []byte        `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Flags            *SRv6SIDFlags `protobuf:"bytes,2,opt,name=flags,proto3" json:"flags,omitempty"`
	EndpointBehavior uint32        `protobuf:"varint,3,opt,name=endpoint_behavior,json=endpointBehavior,proto3" json:"endpoint_behavior,omitempty"`
	// SRv6TLV is one of:
	// - SRv6StructureSubSubTLV
	SubSubTlvs           map[uint32]*SRv6TLV `protobuf:"bytes,4,rep,name=sub_sub_tlvs,json=subSubTlvs,proto3" json:"sub_sub_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SRv6InformationSubTLV) Reset()         { *m = SRv6InformationSubTLV{} }
func (m *SRv6InformationSubTLV) String() string { return proto.CompactTextString(m) }
func (*SRv6InformationSubTLV) ProtoMessage()    {}
func (*SRv6InformationSubTLV) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{3}
}

func (m *SRv6InformationSubTLV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6InformationSubTLV.Unmarshal(m, b)
}
func (m *SRv6InformationSubTLV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6InformationSubTLV.Marshal(b, m, deterministic)
}
func (m *SRv6InformationSubTLV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6InformationSubTLV.Merge(m, src)
}
func (m *SRv6InformationSubTLV) XXX_Size() int {
	return xxx_messageInfo_SRv6InformationSubTLV.Size(m)
}
func (m *SRv6InformationSubTLV) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6InformationSubTLV.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6InformationSubTLV proto.InternalMessageInfo

func (m *SRv6InformationSubTLV) GetSid() []byte {
	if m != nil {
		return m.Sid
	}
	return nil
}

func (m *SRv6InformationSubTLV) GetFlags() *SRv6SIDFlags {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *SRv6InformationSubTLV) GetEndpointBehavior() uint32 {
	if m != nil {
		return m.EndpointBehavior
	}
	return 0
}

func (m *SRv6InformationSubTLV) GetSubSubTlvs() map[uint32]*SRv6TLV {
	if m != nil {
		return m.SubSubTlvs
	}
	return nil
}

// https://tools.ietf.org/html/draft-dawra-bess-srv6-services-02#section-2
type SRv6L3ServiceTLV struct {
	// SRv6TLV is one of:
	// - SRv6InformationSubTLV
	SubTlvs              map[uint32]*SRv6TLV `protobuf:"bytes,1,rep,name=sub_tlvs,json=subTlvs,proto3" json:"sub_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SRv6L3ServiceTLV) Reset()         { *m = SRv6L3ServiceTLV{} }
func (m *SRv6L3ServiceTLV) String() string { return proto.CompactTextString(m) }
func (*SRv6L3ServiceTLV) ProtoMessage()    {}
func (*SRv6L3ServiceTLV) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{4}
}

func (m *SRv6L3ServiceTLV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6L3ServiceTLV.Unmarshal(m, b)
}
func (m *SRv6L3ServiceTLV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6L3ServiceTLV.Marshal(b, m, deterministic)
}
func (m *SRv6L3ServiceTLV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6L3ServiceTLV.Merge(m, src)
}
func (m *SRv6L3ServiceTLV) XXX_Size() int {
	return xxx_messageInfo_SRv6L3ServiceTLV.Size(m)
}
func (m *SRv6L3ServiceTLV) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6L3ServiceTLV.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6L3ServiceTLV proto.InternalMessageInfo

func (m *SRv6L3ServiceTLV) GetSubTlvs() map[uint32]*SRv6TLV {
	if m != nil {
		return m.SubTlvs
	}
	return nil
}

// https://tools.ietf.org/html/rfc8669
type PrefixSID struct {
	// tlv is one of:
	// - IndexLabelTLV Type 1 (not yet implemented)
	// - OriginatorSRGBTLV Type 3 (not yet implemented)
	// - SRv6L3ServiceTLV Type 5
	// - SRv6L2ServiceTLV Type 6 (not yet implemented)
	Tlvs                 []*any.Any `protobuf:"bytes,1,rep,name=tlvs,proto3" json:"tlvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PrefixSID) Reset()         { *m = PrefixSID{} }
func (m *PrefixSID) String() string { return proto.CompactTextString(m) }
func (*PrefixSID) ProtoMessage()    {}
func (*PrefixSID) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{5}
}

func (m *PrefixSID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixSID.Unmarshal(m, b)
}
func (m *PrefixSID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixSID.Marshal(b, m, deterministic)
}
func (m *PrefixSID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixSID.Merge(m, src)
}
func (m *PrefixSID) XXX_Size() int {
	return xxx_messageInfo_PrefixSID.Size(m)
}
func (m *PrefixSID) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixSID.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixSID proto.InternalMessageInfo

func (m *PrefixSID) GetTlvs() []*any.Any {
	if m != nil {
		return m.Tlvs
	}
	return nil
}

type SRv6L3Prefix struct {
	Prefix *Prefix `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Source Autonomous System Number
	Asn uint32 `protobuf:"varint,2,opt,name=asn,proto3" json:"asn,omitempty"`
	// VPN Prefix's Next hop address
	NhAddress []byte `protobuf:"bytes,3,opt,name=nh_address,json=nhAddress,proto3" json:"nh_address,omitempty"`
	// VPN Prefix's RD
	Rd *any.Any `protobuf:"bytes,4,opt,name=rd,proto3" json:"rd,omitempty"`
	// VPN Prefix's RTs
	Rt []*any.Any `protobuf:"bytes,5,rep,name=rt,proto3" json:"rt,omitempty"`
	// VPN Prefix's Prefix SID
	PrefixSid            *PrefixSID `protobuf:"bytes,6,opt,name=prefix_sid,json=prefixSid,proto3" json:"prefix_sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SRv6L3Prefix) Reset()         { *m = SRv6L3Prefix{} }
func (m *SRv6L3Prefix) String() string { return proto.CompactTextString(m) }
func (*SRv6L3Prefix) ProtoMessage()    {}
func (*SRv6L3Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d3ce84a2d2af26, []int{6}
}

func (m *SRv6L3Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRv6L3Prefix.Unmarshal(m, b)
}
func (m *SRv6L3Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRv6L3Prefix.Marshal(b, m, deterministic)
}
func (m *SRv6L3Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRv6L3Prefix.Merge(m, src)
}
func (m *SRv6L3Prefix) XXX_Size() int {
	return xxx_messageInfo_SRv6L3Prefix.Size(m)
}
func (m *SRv6L3Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_SRv6L3Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_SRv6L3Prefix proto.InternalMessageInfo

func (m *SRv6L3Prefix) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SRv6L3Prefix) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func (m *SRv6L3Prefix) GetNhAddress() []byte {
	if m != nil {
		return m.NhAddress
	}
	return nil
}

func (m *SRv6L3Prefix) GetRd() *any.Any {
	if m != nil {
		return m.Rd
	}
	return nil
}

func (m *SRv6L3Prefix) GetRt() []*any.Any {
	if m != nil {
		return m.Rt
	}
	return nil
}

func (m *SRv6L3Prefix) GetPrefixSid() *PrefixSID {
	if m != nil {
		return m.PrefixSid
	}
	return nil
}

func init() {
	proto.RegisterType((*SRv6StructureSubSubTLV)(nil), "apis.SRv6StructureSubSubTLV")
	proto.RegisterType((*SRv6SIDFlags)(nil), "apis.SRv6SIDFlags")
	proto.RegisterType((*SRv6TLV)(nil), "apis.SRv6TLV")
	proto.RegisterType((*SRv6InformationSubTLV)(nil), "apis.SRv6InformationSubTLV")
	proto.RegisterMapType((map[uint32]*SRv6TLV)(nil), "apis.SRv6InformationSubTLV.SubSubTlvsEntry")
	proto.RegisterType((*SRv6L3ServiceTLV)(nil), "apis.SRv6L3ServiceTLV")
	proto.RegisterMapType((map[uint32]*SRv6TLV)(nil), "apis.SRv6L3ServiceTLV.SubTlvsEntry")
	proto.RegisterType((*PrefixSID)(nil), "apis.PrefixSID")
	proto.RegisterType((*SRv6L3Prefix)(nil), "apis.SRv6L3Prefix")
}

func init() { proto.RegisterFile("prefixsid.proto", fileDescriptor_46d3ce84a2d2af26) }

var fileDescriptor_46d3ce84a2d2af26 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0xc7, 0xb1, 0xf3, 0xa7, 0xed, 0xa9, 0xfb, 0x4b, 0xaa, 0x5f, 0x3b, 0xb2, 0xc2, 0xa0, 0xb8,
	0xdd, 0x16, 0xd6, 0xe1, 0x92, 0x86, 0x8d, 0xb1, 0x8b, 0x41, 0x4b, 0x36, 0x08, 0x78, 0x7f, 0xb0,
	0x4b, 0x6f, 0x8d, 0x1c, 0xcb, 0x8e, 0xa9, 0x2b, 0x05, 0x49, 0x36, 0xcb, 0xc3, 0xf4, 0x05, 0xf6,
	0x56, 0x7b, 0x93, 0x21, 0xc9, 0x6e, 0xd2, 0xad, 0xdd, 0xd5, 0x2e, 0x02, 0xca, 0xf9, 0x7e, 0x74,
	0xce, 0xd7, 0xe7, 0xe8, 0x40, 0x6f, 0xc1, 0x49, 0x9a, 0x7f, 0x17, 0x79, 0xe2, 0x2d, 0x38, 0x93,
	0x0c, 0xb5, 0xf1, 0x22, 0x17, 0x07, 0x4f, 0x33, 0xc6, 0xb2, 0x82, 0x9c, 0xea, 0x58, 0x5c, 0xa6,
	0xa7, 0x98, 0x2e, 0x0d, 0x70, 0x00, 0x31, 0x16, 0xc4, 0x9c, 0xdd, 0x1f, 0x36, 0x3c, 0x09, 0x83,
	0xea, 0x6d, 0x28, 0x79, 0x39, 0x93, 0x25, 0x27, 0x61, 0x19, 0x87, 0x65, 0x7c, 0xe9, 0x5f, 0xa1,
	0xd7, 0x80, 0x0a, 0x36, 0xc3, 0x45, 0x14, 0x17, 0x6c, 0x76, 0x1d, 0x15, 0x84, 0x66, 0x72, 0x3e,
	0xb0, 0x0e, 0xad, 0xe1, 0x4e, 0xd0, 0xd7, 0xca, 0x85, 0x12, 0x7c, 0x1d, 0x47, 0xaf, 0x60, 0xd7,
	0xd0, 0x94, 0x25, 0xa4, 0x81, 0x6d, 0x0d, 0xf7, 0xb4, 0xf0, 0x85, 0x25, 0xa4, 0x66, 0x5f, 0x42,
	0x2f, 0x2d, 0xe9, 0x4c, 0xe6, 0x8c, 0x36, 0x64, 0x4b, 0x93, 0xff, 0x35, 0xe1, 0x15, 0x88, 0x79,
	0x56, 0xde, 0x10, 0x2a, 0x1b, 0xb0, 0x6d, 0xc0, 0x26, 0x5c, 0x83, 0x23, 0xd8, 0x93, 0x1c, 0x53,
	0xb1, 0x60, 0x22, 0x5f, 0x4f, 0xdb, 0xd1, 0xf4, 0xff, 0xf7, 0xb4, 0xc7, 0xae, 0xb0, 0x34, 0x15,
	0x44, 0x0e, 0xba, 0x0f, 0x5c, 0xf9, 0xaa, 0x25, 0xf7, 0x39, 0x38, 0xba, 0x57, 0xd3, 0xc9, 0xa7,
	0x02, 0x67, 0x02, 0xed, 0x43, 0x37, 0x2d, 0x70, 0x16, 0x8d, 0x74, 0x57, 0x36, 0x83, 0x8e, 0xfa,
	0x37, 0x72, 0x47, 0xb0, 0xa1, 0x30, 0xd5, 0xc3, 0x17, 0xd0, 0x92, 0x45, 0x35, 0xb0, 0x0e, 0x5b,
	0xc3, 0xed, 0xb3, 0x3d, 0xcf, 0xcc, 0xc4, 0x6b, 0x66, 0xe2, 0x9d, 0xd3, 0x65, 0xa0, 0x00, 0xf7,
	0xd6, 0x86, 0x7d, 0x75, 0x67, 0x4a, 0x53, 0xc6, 0x6f, 0xb0, 0xaa, 0x59, 0x4f, 0xa1, 0x0f, 0x2d,
	0x91, 0x27, 0xba, 0x80, 0x13, 0xa8, 0x23, 0x1a, 0x82, 0xae, 0x23, 0x74, 0x77, 0xb7, 0xcf, 0x90,
	0xa7, 0xe6, 0xed, 0xad, 0x1b, 0x33, 0x46, 0x04, 0x3a, 0x81, 0x5d, 0x42, 0x93, 0x05, 0xcb, 0xa9,
	0x8c, 0x62, 0x32, 0xc7, 0x55, 0xce, 0x78, 0xdd, 0xe9, 0x7e, 0x23, 0x5c, 0xd4, 0x71, 0xf4, 0x19,
	0x1c, 0x51, 0xc6, 0x91, 0xfa, 0xc9, 0xa2, 0x12, 0x83, 0xb6, 0xf6, 0x7c, 0xb2, 0xca, 0xfe, 0x87,
	0x37, 0xaf, 0x7e, 0x2b, 0x45, 0x25, 0x3e, 0x52, 0xc9, 0x97, 0x01, 0x88, 0xbb, 0xc0, 0x81, 0x0f,
	0xbd, 0xdf, 0x64, 0xf5, 0x29, 0xd7, 0x64, 0x59, 0xbf, 0x20, 0x75, 0x44, 0x47, 0xd0, 0xa9, 0x70,
	0x51, 0x92, 0xfa, 0x53, 0x76, 0x56, 0xc5, 0x2e, 0xfd, 0xab, 0xc0, 0x68, 0xef, 0xed, 0x77, 0x96,
	0x7b, 0x6b, 0x41, 0x5f, 0x85, 0xfd, 0x71, 0x48, 0x78, 0x95, 0xcf, 0x88, 0x6a, 0xcd, 0x07, 0xd8,
	0xbc, 0x73, 0x6b, 0x3a, 0x7c, 0xb4, 0x4a, 0xb0, 0x4e, 0x7a, 0xf7, 0x5c, 0x6e, 0x88, 0xda, 0xe2,
	0x14, 0x9c, 0x7f, 0xe5, 0xef, 0x0d, 0x6c, 0x7d, 0xd3, 0x6b, 0x18, 0x4e, 0x27, 0x68, 0x08, 0xed,
	0x35, 0x4f, 0x0f, 0x4f, 0x5d, 0x13, 0xee, 0x4f, 0xcb, 0xbc, 0x28, 0x7f, 0x6c, 0x6e, 0xa3, 0x63,
	0xe8, 0x9a, 0x75, 0xd6, 0x2e, 0xb6, 0xcf, 0x1c, 0x53, 0xd1, 0xa8, 0x41, 0xad, 0x29, 0xa3, 0x58,
	0xd0, 0x7a, 0xbb, 0xd4, 0x11, 0x3d, 0x03, 0xa0, 0xf3, 0x08, 0x27, 0x09, 0x27, 0x42, 0xe8, 0x11,
	0x3b, 0xc1, 0x16, 0x9d, 0x9f, 0x9b, 0x00, 0x3a, 0x06, 0x9b, 0x27, 0x7a, 0x75, 0x1e, 0xf3, 0x63,
	0xf3, 0x44, 0x53, 0x72, 0xd0, 0xf9, 0x8b, 0x6b, 0x9b, 0x4b, 0xe4, 0x01, 0x18, 0x1b, 0x91, 0x7a,
	0x97, 0x5d, 0x9d, 0xb3, 0xb7, 0x6e, 0x33, 0x9c, 0x4e, 0x82, 0x2d, 0x83, 0x84, 0x79, 0x12, 0x77,
	0x75, 0x86, 0xf1, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x9a, 0x4a, 0x05, 0xa8, 0x04, 0x00,
	0x00,
}
