apiVersion: v1
kind: ConfigMap
data:
  gobgp-config.yaml: |
    global:
      config:
        as: 5070
        port: 179
        router-id: 57.112.1.254 
      apply-policy:
        config:
          default-import-policy: accept-route
          default-export-policy: accept-route
    neighbors:
      - config:
          neighbor-address: 192.168.80.128
          peer-as: 5070
          #        ebgp-multihop:
          #          config:
          #            enabled: true
          #            multihop-ttl: 5
        afi-safis:
          - config:
              afi-safi-name: "ipv4-unicast"
          - config:
              afi-safi-name: "ipv6-unicast"
          - config:
              afi-safi-name: "ipv4-labelled-unicast"
          - config:
              afi-safi-name: "ipv6-labelled-unicast"
          - config:
              afi-safi-name: "l3vpn-ipv4-unicast"
          - config:
              afi-safi-name: "l3vpn-ipv6-unicast"
metadata:
  name: gobgpd-config
  namespace: default
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: gobgpd-api
      port: 5051
      protocol: TCP
      targetPort: gobgpd-api
  #    - name: gobgpd-bgp
  #      port: 57179
  #      protocol: TCP
  #      targetPort: gobgpd-bgp
  selector:
    app: gobgpd
  type: ClusterIP
#  externalIPs:
#  - 192.168.80.103
metadata:
  name: gobgpd
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 1
  serviceName: gobgpd
  selector:
    matchLabels:
      app: gobgpd
  template:
    metadata:
      labels:
        app: gobgpd
    spec:
      containers:
        - name: gobgpd
          image: docker.io/sbezverk/gobgpd:v2.15.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: gobgpd-api
              protocol: TCP
          #            - containerPort: 179
          #              name: gobgpd-bgp
          #              protocol: TCP
          args:
            - --config-file
            - "/config/gobgp-config.yaml"
            - --config-type
            - "yaml"
            - --api-hosts
            - "0.0.0.0:50051"
            - --log-level
            - "debug"
            - --log-plain
            - "true"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      nodeSelector:
        jalapeno-app: bgp-speaker
      volumes:
        - name: config-volume
          configMap:
            name: gobgpd-config
metadata:
  name: gobgpd
  namespace: default
