apiVersion: v1
kind: ConfigMap
data:
  gobgp-config.yaml: |
    global:
      config:
        as: 5070
        port: 179
        router-id: 9.9.9.9
      apply-policy:
        config:
          default-import-policy: accept-route
          default-export-policy: accept-route
    neighbors:
      - config:
          neighbor-address: 2001:470:b16e:80::29
          peer-as: 5070
        afi-safis:
          - config:
              afi-safi-name: "ipv6-unicast"
          - config:
              afi-safi-name: "l3vpn-ipv4-unicast"
        transport:
          config:
            passive-mode: true
metadata:
  name: gobgpd-config
  namespace: default
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: gobgpd-api
      port: 5051
      protocol: TCP
      targetPort: gobgpd-api
    - name: gobgpd
      port: 179
      protocol: TCP
      targetPort: gobgpd
  selector:
    app: gobgpd
  type: ClusterIP
  externalIPs:
    - 2001:470:b16e:80::29
metadata:
  name: gobgpd
  namespace: default
  #  labels:
  #  service.kubernetes.io/service-proxy-name: nfproxy
---
apiVersion: apps/v1
kind: StatefulSet
spec:
  replicas: 1
  serviceName: gobgpd
  selector:
    matchLabels:
      app: gobgpd
  template:
    metadata:
      labels:
        app: gobgpd
    spec:
      containers:
        - name: gobgpd
          image: 192.168.80.240:4000/jalapeno/gobgpd-srv6:master
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: gobgpd-api
              protocol: TCP
            - containerPort: 179
              name: gobgpd
              protocol: TCP
          args:
            - --config-file
            - "/config/gobgp-config.yaml"
            - --config-type
            - "yaml"
            - --api-hosts
            - "0.0.0.0:50051"
            - --log-level
            - "debug"
            - --log-plain
            - "true"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      nodeSelector:
        jalapeno.io/infra-app: bgp-speaker
      volumes:
        - name: config-volume
          configMap:
            name: gobgpd-config
metadata:
  name: gobgpd
  namespace: default
