apiVersion: v1
kind: ConfigMap
data:
  gateway-config.yaml: |
metadata:
  name: jalapeno-gateway-config
  namespace: default
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: gateway
      port: 4004
      protocol: TCP
      targetPort: gateway
  selector:
    app: jalapeno-gateway
  type: ClusterIP
  externalIPs:
    - 192.168.80.104
metadata:
  name: jalapeno-gateway
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jalapeno-gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: jalapeno-gateway
  template:
    metadata:
      labels:
        app: jalapeno-gateway
    spec:
      containers:
        - name: jalapeno-gateway
          image: 192.168.80.240:4000/jalapeno/jalapeno-gateway-debug:0.0.0 
          imagePullPolicy: Always
          ports:
            - containerPort: 40040
              name: gateway
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
          args:
            - --database-address
            - "arangodb.jalapeno:8529"
            - --gobgp-address
            - "gobgpd:5051"
            - --v
            - "5"
      volumes:
        - name: config-volume
          configMap:
            name: jalapeno-gateway-config
metadata:
  name: jalapeno-gateway
  namespace: default
